name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test directories
      run: |
        mkdir -p test_files
        mkdir -p reports
        
    - name: Run tests with Chrome
      run: |
        pytest tests/test_contact.py tests/test_registration.py --browser=chrome -v
        
    - name: Run tests with Firefox
      run: |
        pytest tests/test_contact.py tests/test_registration.py --browser=firefox -v