name: CI for QA Automation Challenge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: >-
          --shm-size 2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests (Firefox)
      env:
        DISPLAY: ":99"
      run: pytest --browser=firefox --headless --disable-warnings

    - name: Run tests (Chrome)
      env:
        DISPLAY: ":99"
      run: pytest --browser=chrome --headless --disable-warnings
